/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import clases.conectate;
import clases.sqlclass;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import ve.edu.ucab.keyboard.Keyboard;
import ve.edu.ucab.logic.LogicComponent;
import ve.edu.ucab.logic.LogicListComponent;

/**
 *
 * @author KONESH
 */
public class iniciar_sesion extends javax.swing.JFrame {

    private Keyboard keyboard;
    sqlclass funcion = new sqlclass();
    sqlclass general = new sqlclass();
    conectate conexion = new conectate();
    String fecha_sistema, insumos_like;
    principal ventana_principal;

    public static String id_usuario_global; // variable publica global para asignar el id del usuario
    public static String nombre_usuario_global, apellidos_usuario_global, puesto_global, administrador_global, ventas_global, caja_global, insumos_global, compras_global, utilerias_global;

    /**
     * Creates new form iniciar_sesion
     */
    public iniciar_sesion() {
        initComponents();

        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/cuichi_mini.png"));
        setIconImage(icon);

        this.setLocationRelativeTo(null);
        LogicListComponent components = new LogicListComponent();

        components.addComponent(new LogicComponent(this.txt_contraseña, 1, false, true, false, false));

        keyboard = new Keyboard(components, true);
        //keyboard.
        panel_teclado.setLayout(new GridLayout(1, 1));
        panel_teclado.add(keyboard);
    }

    public void conectar() {
        // conexion.setIp(IpServer);
        conexion.conectate();
    }

    public void entrar() {

        String pswd = new String(this.txt_contraseña.getPassword());
        //String area = null, priv = null;
        int inm = 0;
        conectar();
        try {
            Connection con = conexion.getConnection();
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM empleado WHERE contraseña = '" + pswd + "'");
            if (rs.first()) {
                inm = 1;
                id_usuario_global = rs.getString("id_empleado");
                nombre_usuario_global = rs.getString("nombre");
                apellidos_usuario_global = rs.getString("apellidos");
                puesto_global = rs.getString("puesto");
                administrador_global = rs.getString("administrador");

                System.out.println("administrador_global: " + administrador_global);

                ventas_global = rs.getString("ventas");
                caja_global = rs.getString("caja");
                insumos_global = rs.getString("insumos");
                compras_global = rs.getString("compras");
                utilerias_global = rs.getString("utilerias");
            }
            con.close();
            if (inm == 1) {
                ventana_principal = new principal();

                ventana_principal.show();

                this.txt_contraseña.setText("");
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "No coincide la contraseña ", "Error ", JOptionPane.ERROR_MESSAGE);
                this.txt_contraseña.setText("");
                this.txt_contraseña.requestFocus();
            }
        } catch (SQLException | HeadlessException ex) {
            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Error con la conexión a la base de datos: " + ex, "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbtn_iniciar_sesion = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        panel_teclado = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jbtn_iniciar_sesion.setText("Ir");
        Jbtn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_iniciar_sesionActionPerformed(evt);
            }
        });

        txt_contraseña.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contraseñaFocusGained(evt);
            }
        });
        txt_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contraseñaKeyPressed(evt);
            }
        });

        jLabel2.setText("Contraseña:");

        panel_teclado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_tecladoLayout = new javax.swing.GroupLayout(panel_teclado);
        panel_teclado.setLayout(panel_tecladoLayout);
        panel_tecladoLayout.setHorizontalGroup(
            panel_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        panel_tecladoLayout.setVerticalGroup(
            panel_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuichi_mini.png"))); // NOI18N
        jLabel92.setToolTipText("");
        jLabel92.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jbtn_iniciar_sesion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jbtn_iniciar_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_iniciar_sesionActionPerformed
        // TODO add your handling code here:
        if ((this.txt_contraseña.getPassword().equals(""))) {
            JOptionPane.showMessageDialog(null, "Introduce tu contraseña para ingresar....", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            entrar();
        }
    }//GEN-LAST:event_Jbtn_iniciar_sesionActionPerformed

    private void txt_contraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contraseñaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            entrar();
        }

    }//GEN-LAST:event_txt_contraseñaKeyPressed

    private void txt_contraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contraseñaFocusGained
        // TODO add your handling code here:
        if (keyboard != null) {
            keyboard.setComponentSelected(2, true);
        }
    }//GEN-LAST:event_txt_contraseñaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciar_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciar_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_iniciar_sesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel panel_teclado;
    private javax.swing.JPasswordField txt_contraseña;
    // End of variables declaration//GEN-END:variables
}
