/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import clases.sqlclass;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static restaurante.principal.id_categorias_seleccion;
import static restaurante.principal.id_venta_global;

/**
 *
 * @author Gerardo Torreblanca
 */
public class permisos_empleados extends javax.swing.JDialog {
    
    sqlclass funcion = new sqlclass();
    Object[][] dtconduc;
    String administrador, ventas, caja, insumos, compras, utilerias;

    /**
     * Creates new form mesas
     */
    public permisos_empleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jbtn_guardar.setEnabled(false);
        lbl_nombre_empleado.setText("Elija permisos para: " + (String) principal.tabla_empleados.getValueAt(principal.tabla_empleados.getSelectedRow(), 1) + " " + (String) principal.tabla_empleados.getValueAt(principal.tabla_empleados.getSelectedRow(), 2));
        traer_permisos();
    }
    
    public void traer_permisos() {
//        funcion.conectate();
        String[] colName = {"id_empleado", "administrador", "ventas", "caja", "insumos", "compras", "utilerias"};
        
        dtconduc = funcion.GetTabla(colName, "clientes", "SELECT id_empleado,administrador,ventas,caja,insumos,compras,utilerias FROM empleado WHERE id_empleado =" + (String) principal.tabla_empleados.getValueAt(principal.tabla_empleados.getSelectedRow(), 0) + " ;");
        System.out.println("dtconduc[0][0]: " + dtconduc[0][0]);
        if (dtconduc[0][1].equals("1")) { // es administrador

            check_admin.setSelected(true);
        } else {
            
            if (dtconduc[0][2].equals("1")) { // ventas
                check_ventas.setSelected(true);
            }
            if (dtconduc[0][3].equals("1")) { // caja
                check_caja.setSelected(true);
            }
            if (dtconduc[0][4].equals("1")) { // insumos
                check_insumos.setSelected(true);
            }
            if (dtconduc[0][5].equals("1")) { // compras
                check_compras.setSelected(true);
            }
            if (dtconduc[0][6].equals("1")) { // utilerias
                check_utilerias.setSelected(true);
            }
        }
        
//        funcion.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombre_empleado = new javax.swing.JLabel();
        check_admin = new javax.swing.JCheckBox();
        check_ventas = new javax.swing.JCheckBox();
        check_caja = new javax.swing.JCheckBox();
        check_insumos = new javax.swing.JCheckBox();
        check_compras = new javax.swing.JCheckBox();
        check_utilerias = new javax.swing.JCheckBox();
        jbtn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_nombre_empleado.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        check_admin.setText("Administrador");
        check_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_adminActionPerformed(evt);
            }
        });

        check_ventas.setText("Ventas");
        check_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_ventasActionPerformed(evt);
            }
        });

        check_caja.setText("Caja");
        check_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_cajaActionPerformed(evt);
            }
        });

        check_insumos.setText("Insumos");
        check_insumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_insumosActionPerformed(evt);
            }
        });

        check_compras.setText("Compras");
        check_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_comprasActionPerformed(evt);
            }
        });

        check_utilerias.setText("Utilerias");
        check_utilerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_utileriasActionPerformed(evt);
            }
        });

        jbtn_guardar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jbtn_guardar.setText("Guardar...");
        jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_utilerias)
                            .addComponent(check_compras)
                            .addComponent(check_insumos)
                            .addComponent(check_caja)
                            .addComponent(check_ventas)
                            .addComponent(check_admin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombre_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_guardar)
                .addGap(23, 23, 23)
                .addComponent(check_admin)
                .addGap(36, 36, 36)
                .addComponent(check_ventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_caja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_insumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_compras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_utilerias)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_adminActionPerformed
        // TODO add your handling code here:
        check_ventas.setSelected(false);
        check_caja.setSelected(false);
        check_compras.setSelected(false);
        check_insumos.setSelected(false);
        check_utilerias.setSelected(false);
        jbtn_guardar.setEnabled(true);

    }//GEN-LAST:event_check_adminActionPerformed

    private void check_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ventasActionPerformed
        // TODO add your handling code here:
        jbtn_guardar.setEnabled(true);
        check_admin.setSelected(false);
    }//GEN-LAST:event_check_ventasActionPerformed

    private void check_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_cajaActionPerformed
        // TODO add your handling code here:
        jbtn_guardar.setEnabled(true);
        check_admin.setSelected(false);
    }//GEN-LAST:event_check_cajaActionPerformed

    private void check_insumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_insumosActionPerformed
        // TODO add your handling code here:
        jbtn_guardar.setEnabled(true);
        check_admin.setSelected(false);
    }//GEN-LAST:event_check_insumosActionPerformed

    private void check_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_comprasActionPerformed
        // TODO add your handling code here:
        jbtn_guardar.setEnabled(true);
        check_admin.setSelected(false);
    }//GEN-LAST:event_check_comprasActionPerformed

    private void check_utileriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_utileriasActionPerformed
        // TODO add your handling code here:
        jbtn_guardar.setEnabled(true);
        check_admin.setSelected(false);
    }//GEN-LAST:event_check_utileriasActionPerformed

    private void jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_guardarActionPerformed
        // TODO add your handling code here:
//        funcion.conectate();
        
        if (check_admin.isSelected()) {
            administrador = "1";
        } else {
            administrador = "0";
        }
        
        if (check_ventas.isSelected()) {
            ventas = "1";
        } else {
            ventas = "0";
        }
        
        if (check_caja.isSelected()) {
            caja = "1";
        } else {
            caja = "0";
        }
        
        if (check_insumos.isSelected()) {
            insumos = "1";
        } else {
            insumos = "0";
        }
        
        if (check_compras.isSelected()) {
            compras = "1";
        } else {
            compras = "0";
        }
        
        if (check_utilerias.isSelected()) {
            utilerias = "1";
        } else {
            utilerias = "0";
        }
        
        String datos[] = {administrador, ventas, caja, insumos, compras, utilerias, (String) principal.tabla_empleados.getValueAt(principal.tabla_empleados.getSelectedRow(), 0)};
        funcion.UpdateRegistro(datos, "update empleado set administrador=?,ventas=?,caja=?,insumos=?,compras=?,utilerias=? where id_empleado=?");
        
//        funcion.desconecta();
        
        JOptionPane.showMessageDialog(null, "Se actualizo con exito...", "Error", JOptionPane.INFORMATION_MESSAGE);
        jbtn_guardar.setEnabled(false);
        
    }//GEN-LAST:event_jbtn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(permisos_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(permisos_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(permisos_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(permisos_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                permisos_empleados dialog = new permisos_empleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox check_admin;
    private javax.swing.JCheckBox check_caja;
    private javax.swing.JCheckBox check_compras;
    private javax.swing.JCheckBox check_insumos;
    private javax.swing.JCheckBox check_utilerias;
    private javax.swing.JCheckBox check_ventas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_guardar;
    private javax.swing.JLabel lbl_nombre_empleado;
    // End of variables declaration//GEN-END:variables
}
