/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import clases.conectate;
import clases.sqlclass;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import ve.edu.ucab.keyboard.Keyboard;
import ve.edu.ucab.logic.LogicComponent;
import ve.edu.ucab.logic.LogicListComponent;

/**
 *
 * @author KONESH
 */
public class ver_notas_platillos extends javax.swing.JDialog {

    private Keyboard keyboard;
    sqlclass funcion = new sqlclass();
    conectate conexion = new conectate();

    /**
     * Creates new form ver_notas_platillos
     */
    public ver_notas_platillos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        traer_datos();
         txt_nota_1.requestFocus();
        //txt_nota_1.setEditable(false);
        //txt_nota_2.setEditable(false);
        //Jtbn_guardar.setEnabled(false);
        this.lbl_nombre_platillo.setText(principal.platillo_global);

        LogicListComponent components = new LogicListComponent();

        components.addComponent(new LogicComponent(this.txt_nota_1, 1, false, false, true, true));
        components.addComponent(new LogicComponent(this.txt_nota_2, 2, true, false, true, false));

        keyboard = new Keyboard(components, true);
        //keyboard.
        panel_teclado.setLayout(new GridLayout(1, 1));
        panel_teclado.add(keyboard);
    }

    public void conectar() {
        // conexion.setIp(IpServer);
        conexion.conectate();
    }

    public void desconectar() {
        conexion.desconectar();
    }
    public void guardar(){
    
//            funcion.conectate();
            String datos[] = {this.txt_nota_1.getText(), this.txt_nota_2.getText(), principal.id_detalle_categoria_global, principal.id_venta_global};
            funcion.UpdateRegistro(datos, "update detalle_venta set nota1=?,nota2=? where id_detalle_categorias=? AND id_venta=?");
//            funcion.desconecta();
          //  JOptionPane.showMessageDialog(null, "Se actualizo con exito.", "Actualizacion", JOptionPane.INFORMATION_MESSAGE);
        //}
        /*this.txt_nota_1.setEditable(false);
        this.txt_nota_2.setEditable(false);
        Jtbn_guardar.setEnabled(false);*/
            principal.validar_ventana_notas = true;
            this.dispose();
    
    }

    public void traer_datos() {
        byte[] img = null;
        conectar();
        try {
            System.out.println("id: " + principal.id_detalle_categoria_global);
            Connection con = conexion.getConnection();
            Statement s = con.createStatement();
            ResultSet res = s.executeQuery("SELECT * FROM detalle_venta where id_detalle_categorias = " + principal.id_detalle_categoria_global + " AND id_venta=" + principal.id_venta_global + "");
            res.next();

            String nota1, nota2;
            nota1 = (res.getString("nota1"));
            nota2 = (res.getString("nota2"));
            
            if (nota1 == null) {
                this.txt_nota_1.setText("");
            } else {
                this.txt_nota_1.setText(nota1);
            }
            if (nota2 == null) {
                this.txt_nota_2.setText("");
            } else {
                this.txt_nota_2.setText(nota2);
            }
            res.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_nota_1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_nota_2 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombre_platillo = new javax.swing.JLabel();
        Jtbn_guardar = new javax.swing.JButton();
        panel_teclado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nota_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nota_1FocusGained(evt);
            }
        });
        txt_nota_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nota_1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_nota_1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 349, 70));

        txt_nota_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nota_2FocusGained(evt);
            }
        });
        txt_nota_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nota_2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt_nota_2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 320, 70));

        jLabel1.setText("Nota 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Nota 2:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        lbl_nombre_platillo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nombre_platillo.setToolTipText("");
        getContentPane().add(lbl_nombre_platillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 310, 24));

        Jtbn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/database-check-icon.png"))); // NOI18N
        Jtbn_guardar.setToolTipText("Guardar");
        Jtbn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtbn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(Jtbn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 30));

        panel_teclado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_tecladoLayout = new javax.swing.GroupLayout(panel_teclado);
        panel_teclado.setLayout(panel_tecladoLayout);
        panel_tecladoLayout.setHorizontalGroup(
            panel_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        panel_tecladoLayout.setVerticalGroup(
            panel_tecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        getContentPane().add(panel_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 670, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtbn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtbn_guardarActionPerformed
       guardar();

    }//GEN-LAST:event_Jtbn_guardarActionPerformed

    private void txt_nota_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nota_2FocusGained
        // TODO add your handling code here:
        if (keyboard != null) {
            keyboard.setComponentSelected(2, true);
        }
    }//GEN-LAST:event_txt_nota_2FocusGained

    private void txt_nota_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nota_1FocusGained
        // TODO add your handling code here:
        if (keyboard != null) {
            keyboard.setComponentSelected(1, true);
        }
    }//GEN-LAST:event_txt_nota_1FocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void txt_nota_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nota_1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            guardar();
        }
    }//GEN-LAST:event_txt_nota_1KeyPressed

    private void txt_nota_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nota_2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            guardar();
        }
    }//GEN-LAST:event_txt_nota_2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ver_notas_platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ver_notas_platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ver_notas_platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ver_notas_platillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ver_notas_platillos dialog = new ver_notas_platillos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jtbn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_nombre_platillo;
    private javax.swing.JPanel panel_teclado;
    private javax.swing.JTextPane txt_nota_1;
    private javax.swing.JTextPane txt_nota_2;
    // End of variables declaration//GEN-END:variables
}
