/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package restaurante;

import clases.sqlclass;
import java.awt.GridLayout;
import java.security.Principal;
import javax.swing.JOptionPane;
import static restaurante.principal.total_pagar;
import ve.edu.ucab.keyboard.Keyboard;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.SwingConstants;

/**
 *
 * @author KONESH
 */
public class WinSearchElement extends javax.swing.JDialog {
    private Keyboard keyboard;
    sqlclass funcion = new sqlclass();
    /**
     * Creates new form cerrar_venta
     */
    public static String por_apertura,comentario;
    public WinSearchElement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.txtSearchElement.requestFocus();
        formato_tabla();
        lblInfoHelp.setText("Recuerda utilizar la tecla ENTER para tu comodidad!");
        
        
    }
    
 
  
  public String EliminaCaracteres(String s_cadena, String s_caracteres){
  String nueva_cadena = "";
  Character caracter = null;
  boolean valido = true;
 
  /* Va recorriendo la cadena s_cadena y copia a la cadena que va a regresar,
     sólo los caracteres que no estén en la cadena s_caracteres */
  for (int i=0; i<s_cadena.length(); i++)
      {
       valido = true;
       for (int j=0; j<s_caracteres.length(); j++)
           {
            caracter = s_caracteres.charAt(j);
 
            if (s_cadena.charAt(i) == caracter)
               {
                valido = false;
                break;
               }
           }
       if (valido)
           nueva_cadena += s_cadena.charAt(i);
      }
 
  return nueva_cadena;
}
  
   public void formato_tabla() {
        String[] columNames = {"Codigo", "Nombre", "Precio"};
        Object[][] data = {{"", "", ""}};
        DefaultTableModel TableModel = new DefaultTableModel(data, columNames);
        tableSearchElements.setModel(TableModel);

         int[] anchos = {80, 200, 100};
        for (int inn = 0; inn < tableSearchElements.getColumnCount(); inn++) {
            tableSearchElements.getColumnModel().getColumn(inn).setPreferredWidth(anchos[inn]);
        }

        try {
            DefaultTableModel temp = (DefaultTableModel) tableSearchElements.getModel();
            temp.removeRow(temp.getRowCount() - 1);

        } catch (ArrayIndexOutOfBoundsException e) {
            ;
        }

       

    }
  
  public void tableSearchElements_like(String item) {
      
        // funcion.conectate();
        tableSearchElements.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        String[] columNames = {"Codigo", "Nombre", "Precio"};
        String[] colName = {"id_detalle_categorias", "descripcion", "precio_publico"};
        //nombre de columnas, tabla, instruccion sql        
        Object[][] dtconduc = funcion.GetTabla(colName, "detalle_categorias", "SELECT d.`id_detalle_categorias`, d.`descripcion`, d.`precio_publico` FROM restaurante.detalle_categorias d WHERE d.`activo`='1' AND d.`descripcion` LIKE '%" + item + "%' ORDER BY d.`descripcion`"); //WHERE apellidos LIKE '%" + this.txt_filtro_clientes.getText() + "%'
        DefaultTableModel datos = new DefaultTableModel(dtconduc, columNames);
        tableSearchElements.setModel(datos);

        DefaultTableCellRenderer centrar = new DefaultTableCellRenderer();
        centrar.setHorizontalAlignment(SwingConstants.CENTER);

        int[] anchos = {80, 200, 100};

        for (int inn = 0; inn < tableSearchElements.getColumnCount(); inn++) {
            tableSearchElements.getColumnModel().getColumn(inn).setPreferredWidth(anchos[inn]);
        }

//        tableSearchElements.getColumnModel().getColumn(0).setMaxWidth(0);
//        tableSearchElements.getColumnModel().getColumn(0).setMinWidth(0);
//        tableSearchElements.getColumnModel().getColumn(0).setPreferredWidth(0);
        tableSearchElements.getColumnModel().getColumn(2).setCellRenderer(centrar);

//        funcion.desconecta();
  
  }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jbtn_ok = new javax.swing.JButton();
        Jbtn_cancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSearchElements = new javax.swing.JTable(){public boolean isCellEditable(int rowIndex,int colIndex){return false;}};
        txtSearchElement = new javax.swing.JTextField();
        lblSeleccion = new javax.swing.JLabel();
        lblInfoHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Buscar elemento en la bd");

        Jbtn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actions-dialog-ok-apply-icon.png"))); // NOI18N
        Jbtn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_okActionPerformed(evt);
            }
        });

        Jbtn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/go-back-icon.png"))); // NOI18N
        Jbtn_cancelar.setToolTipText("Cancelar");
        Jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_cancelarActionPerformed(evt);
            }
        });

        tableSearchElements.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        tableSearchElements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSearchElements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSearchElementsMouseClicked(evt);
            }
        });
        tableSearchElements.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableSearchElementsKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tableSearchElements);

        txtSearchElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchElementActionPerformed(evt);
            }
        });
        txtSearchElement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchElementKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchElementKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(168, 168, 168)
                                .addComponent(Jbtn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearchElement)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jbtn_cancelar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Jbtn_ok, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchElement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_okActionPerformed
        
        if (tableSearchElements.getSelectedRow() != -1) {           
            int x = tableSearchElements.getSelectedRow();
            String id = (String) tableSearchElements.getValueAt(x, 0);
            if(principal.addItems(id))               
                this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para agregar el elemento.  ", "Error  ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_Jbtn_okActionPerformed

    private void Jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_cancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_Jbtn_cancelarActionPerformed

    private void tableSearchElementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSearchElementsMouseClicked
        int x = tableSearchElements.getSelectedRow();
        lblSeleccion.setText(tableSearchElements.getValueAt(x, 1).toString());
        if (evt.getClickCount() == 2) {            
            String id = (String) tableSearchElements.getValueAt(x, 0);
            if(principal.addItems(id))
               this.dispose();
        }
    }//GEN-LAST:event_tableSearchElementsMouseClicked

    private void tableSearchElementsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableSearchElementsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSearchElementsKeyPressed

    private void txtSearchElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchElementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchElementActionPerformed

    private void txtSearchElementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchElementKeyReleased
        if (evt.getKeyCode() != 10) {
        tableSearchElements_like(this.txtSearchElement.getText());
            if(tableSearchElements.getRowCount() == 0){
                lblInfoHelp.setText("Ops! sin resultados :(");
            }else{
                int z = tableSearchElements.getRowCount();
                lblInfoHelp.setText(z == 1 ? z+" elemento encontrado... =) " : z+" elementos encontrados... =)");
            }
        }
    }//GEN-LAST:event_txtSearchElementKeyReleased

    private void txtSearchElementKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchElementKeyPressed
       if (evt.getKeyCode() == 10) {
           if(tableSearchElements.getRowCount() == 1){
            String id = (String) tableSearchElements.getValueAt(0, 0);
            if(principal.addItems(id))
               this.dispose();  
           }else{
               lblInfoHelp.setText("Accion +Enter solo funciona con un elemento en la lista");
           }
            
        }
    }//GEN-LAST:event_txtSearchElementKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinSearchElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinSearchElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinSearchElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinSearchElement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinSearchElement dialog = new WinSearchElement(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_cancelar;
    private javax.swing.JButton Jbtn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblInfoHelp;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JTable tableSearchElements;
    private javax.swing.JTextField txtSearchElement;
    // End of variables declaration//GEN-END:variables
}
